### ISSUE TITLE
Case eksiklikleri

### ISSUE THREAD

**Issue by barancanatbas** [SametAvcii/StudentPlaningApp#1]
Öncelikle eline sağlık, şuanda başvurunu değerlendirmekteyiz projeni incelerken bir kaç eksiklik ve farklıkla karşılaştık bunları senin ile paylaşmak istedik.

migrate için kullanılan sql dosyaları eksik, Plans tablosundaki sql querisinde foreign key yok.
user/id , user/plan/id  routlarında id değerlerini kullanıcıdan almak gerekir.
yeni plan ekleme veya plan güncelleme alanlarında aynı tarih ve saatte başka plan olup olmadığını kontrol etmeni istemiştik fakat göremedik, bu madde bizim için önemli.
migrate için gorm'un kendi migrate methodunu kullanabilirsin.

**Comment by SametAvcii** [comment]
Öncelikle teşekkürler geri bildirim için migrate için gorm paketinin Auto migrate fonksiyonunu kullandım. Foreign key'i kendisi ayarlıyormuş. api/plans.go/CreatePlan fonksiyonu içinde görebilirsiniz. Plan kontrolüne gelince CheckPlan adında bir fonksiyon oluşturdum. Aynı gün ve saate denk gelen vs. kontrol ediyor. Yine State durumlarınıda kontrol etmektedir. Bu fonksiyonuda plans.go dosyasında bulabilirsinix. Routerlarıda istediğiniz şekilde düzenledim. CheckPlan fonksiyonu geliştirilebilir yeterli olmaması durumunda bana tekrardan bildirirseniz yine güncellerim.
